# Generated by Django 3.1.3 on 2020-11-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'default_related_name': 'rankings', 'ordering': ['ranking']},
        ),
    ]
