# Generated by Django 3.1.3 on 2020-11-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0007_remove_taskresult_hidden'),
        ('podminer', '0002_auto_20201112_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTaskResult',
            fields=[
                ('taskresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_results.taskresult')),
            ],
            options={
                'db_table': 'podminer_update_task_result',
            },
            bases=('django_celery_results.taskresult',),
        ),
    ]
