# Generated by Django 3.1.3 on 2020-11-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0003_updatetaskresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatetaskresult',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
