# Generated by Django 3.1.3 on 2020-11-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0004_updatetaskresult_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatetaskresult',
            name='task_type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], default='unspecified', max_length=100),
            preserve_default=False,
        ),
    ]
