# Generated by Django 3.1.3 on 2020-11-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0005_updatetaskresult_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='store_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rankinghistory',
            name='store_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
