# Generated by Django 3.1.3 on 2020-11-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0006_auto_20201119_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='store_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankinghistory',
            name='store_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
