# Generated by Django 3.1.3 on 2020-12-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0007_auto_20201119_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='last_ranking',
            field=models.IntegerField(default=-1),
        ),
    ]
