# Generated by Django 3.1.4 on 2020-12-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0013_powerranking1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PowerRanking',
        ),
    ]
