# Generated by Django 3.1.3 on 2020-12-03 13:13

from django.db import migrations
import datetime

def forwards(apps, schema_editor):
    Ranking = apps.get_model('podminer.Ranking')
    RankingHistory = apps.get_model('podminer.RankingHistory')
    RankingHistory.objects.filter(updated__date='2020-12-03').delete()
    RankingHistory.objects.filter(updated__date='2020-12-05').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0014_delete_powerranking'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

