# Generated by Django 3.1.4 on 2020-12-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0015_faultydatafix'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxGlobalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=237)),
                ('updated', models.DateField()),
            ],
            options={
                'db_table': 'podminer_mgs',
                'default_related_name': 'mgs',
            },
        ),
    ]
