# Generated by Django 3.1.3 on 2020-12-03 13:13

from django.db import migrations
import datetime
from django.db.models import Count

def forwards(apps, schema_editor):
    RankingHistory = apps.get_model('podminer.RankingHistory')
    MaxGlobalScore = apps.get_model('podminer.MaxGlobalScore')
    cc=0
    prqs = RankingHistory.objects.filter(show__podcast_id=863897795,ranking__lt=21).values('show__podcast_id','updated__date').annotate(score=Count('updated__date')).order_by('updated__date')         #to get dates by most popular show
    print("first complete")
    for ins in prqs:
        powerranking_queryset = RankingHistory.objects.filter(ranking__lt=21,updated__date=ins['updated__date']).values('show__podcast_id','updated__date').annotate(score=Count('show__podcast_id')).order_by('-score')[:2]   
        max_score=237
        if powerranking_queryset:
            max_score=powerranking_queryset.first()['score']
        MaxGlobalScore(
            score=max_score,
            updated=ins['updated__date'],
        ).save()
        cc+=1
        print(cc) #to keep track of progress
        print(max_score)
        print(ins['updated__date'])


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0016_maxglobalscore'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

