# Generated by Django 3.1.5 on 2021-01-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_report_followed'),
        ('podminer', '0017_mgsupd'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTop100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('last_ranking', models.IntegerField(default=-1)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='globaltop100', to='core.show')),
            ],
            options={
                'db_table': 'podminer_globaltop100',
                'default_related_name': 'globaltop100',
            },
        ),
    ]
