# Generated by Django 3.1.5 on 2021-01-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0018_globaltop100'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltop100',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
