# Generated by Django 3.1.5 on 2021-01-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_report_followed'),
        ('podminer', '0020_powerrankinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTop100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('ranking', models.IntegerField()),
                ('last_ranking', models.IntegerField(default=-1)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='genretop100', to='core.genre')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='genretop100', to='core.show')),
            ],
            options={
                'db_table': 'podminer_genretop100',
                'default_related_name': 'genretop100',
            },
        ),
    ]
