# Generated by Django 3.1.5 on 2021-01-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_report_followed'),
        ('podminer', '0021_genretop100'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionTop100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('ranking', models.IntegerField()),
                ('last_ranking', models.IntegerField(default=-1)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='regiontop100', to='core.show')),
            ],
            options={
                'db_table': 'podminer_regiontop100',
                'default_related_name': 'regiontop100',
            },
        ),
    ]
