# Generated by Django 3.1.5 on 2021-01-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0023_countrytop100'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerrankinghistory',
            name='val',
            field=models.IntegerField(default=0),
        ),
    ]
