# Generated by Django 3.1.5 on 2021-01-29 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podminer', '0024_powerrankinghistory_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerrankinghistory',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
