# Generated by Django 3.1.6 on 2021-02-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_report_followed'),
        ('podminer', '0025_auto_20210129_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistCountryGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bcg', to='core.country')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bcg', to='core.genre')),
            ],
            options={
                'db_table': 'podminer_bcg',
                'default_related_name': 'bcg',
            },
        ),
        migrations.DeleteModel(
            name='MaxGlobalScore',
        ),
    ]
