# Generated by Django 3.1.3 on 2020-11-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_genre_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='url',
            field=models.TextField(),
        ),
    ]
