# Generated by Django 3.1.3 on 2020-11-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201119_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='slug',
        ),
    ]
