# Generated by Django 3.1.3 on 2020-11-26 06:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_show_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
