# Generated by Django 3.1.3 on 2020-11-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201126_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shows_followed',
            field=models.ManyToManyField(blank=True, to='core.Show'),
        ),
    ]
