# Generated by Django 3.1.3 on 2020-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_shows_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='hero_image',
            field=models.TextField(null=True),
        ),
    ]
