# Generated by Django 3.1.3 on 2020-11-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_show_hero_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='hero_image',
            new_name='image_link',
        ),
    ]
