# Generated by Django 3.1.3 on 2020-12-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201127_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.TextField(default='nothing'),
        ),
    ]
