# Generated by Django 3.1.3 on 2020-12-03 13:13

from django.db import migrations

def forwards(apps, schema_editor):
    Show = apps.get_model('core.Show')
    for show in Show.objects.all():
        new_slug = show.url.split('/')[-2]
        show.slug = new_slug
        show.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201203_1312'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
