# Generated by Django 3.1.3 on 2020-12-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shows_slug_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFilter',
            fields=[
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'countryfilter',
            },
        ),
        migrations.CreateModel(
            name='GenreFilter',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='genre_filter', to='core.countryfilter')),
            ],
            options={
                'db_table': 'genrefilter',
                'default_related_name': 'genre_filter',
            },
        ),
    ]
