# Generated by Django 3.1.3 on 2020-12-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_genrefilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField(default=3)),
                ('name', models.CharField(default='noname', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='genre_filter', to='core.countryfilter')),
            ],
            options={
                'db_table': 'genrefilter',
                'default_related_name': 'genre_filter',
            },
        ),
    ]
