# Generated by Django 3.1.4 on 2020-12-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_show_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region_code',
            field=models.CharField(default='nocode', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='regionname',
            field=models.CharField(default='noname', max_length=100),
        ),
    ]
