# Generated by Django 3.1.3 on 2020-12-03 13:13

from django.db import migrations
import datetime
from hdx.location.country import Country as Country2

def forwards(apps, schema_editor):
    Country = apps.get_model('core.Country')

    cc=0
    for cnt in Country.objects.all():
        if Country2.get_country_info_from_iso2(cnt.country_code)['#region+name+preferred+sub']:
            cnt.regionname=Country2.get_country_info_from_iso2(cnt.country_code)['#region+name+preferred+sub']
            cnt.region_code=Country2.get_country_info_from_iso2(cnt.country_code)['#region+code+sub']
            cnt.save()
        elif Country2.get_country_info_from_iso2(cnt.country_code)['#region+main+name+preferred']:
            cnt.regionname=Country2.get_country_info_from_iso2(cnt.country_code)['#region+main+name+preferred']
            cnt.region_code=Country2.get_country_info_from_iso2(cnt.country_code)['#region+code+main']
            cnt.save()
        else:
            cnt.regionname=Country2.get_country_info_from_iso2(cnt.country_code)['#country+name+preferred']
            cnt.region_code=Country2.get_country_info_from_iso2(cnt.country_code)['#country+code+v_iso2']
            cnt.save()
        cc+=1
        if cc%300==0:
            print(cc) #to keep track of progress


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201218_0918'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

