# Generated by Django 3.1.3 on 2020-12-03 13:13

from django.db import migrations

def forwards(apps, schema_editor):
    Show = apps.get_model('core.Show')
    cc=0
    for show in Show.objects.all():
        new_slug = show.url.split('/')[-2]
        show.slug = new_slug
        show.save()
        cc+=1
        if cc%300==0:
            print(new_slug)
            print(cc) #to keep track of progress


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fin_cnt'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
