# Generated by Django 3.1.3 on 2020-12-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_slugfixesdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreFilter',
        ),
    ]
