# Generated by Django 3.1.4 on 2021-01-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_deletecountryfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_status',
            field=models.IntegerField(default=1),
        ),
    ]
