# Generated by Django 3.1.5 on 2021-01-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_followed',
            field=models.ManyToManyField(blank=True, related_name='report_followed', to='core.Show'),
        ),
    ]
