# Generated by Django 3.1.6 on 2021-02-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_report_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='releaseDate',
            field=models.CharField(default='19 May 2016', max_length=200),
        ),
    ]
