# Generated by Django 3.1.6 on 2021-02-10 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_show_releasedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('audio_link', models.URLField(max_length=1000)),
                ('image_link', models.URLField(max_length=1000)),
                ('description', models.TextField()),
                ('released', models.DateTimeField()),
                ('duration', models.TextField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.show')),
            ],
            options={
                'db_table': 'episodes',
            },
        ),
    ]
