# Generated by Django 3.1.6 on 2021-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_link',
            field=models.URLField(default='no_audio_link', max_length=1000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(default='no_description'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.TextField(default='no_duration'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image_link',
            field=models.URLField(default='no_image_link', max_length=1000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='released',
            field=models.DateTimeField(default='1800-01-01'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.TextField(default='no_title'),
        ),
    ]
